root:
    database:
        dbname: hobocta_transactions
        host: 127.0.0.1
        port: 3306
        username: root
        password:

    balance:
        # количество знаков после запятой (для вывода и для ввода сумм)
        decimals: 6
